# Exploration de l'API OpenWeather
Le but de ce notebook est d'explorer les données envoyées par l'API d'OpenWeather dans le but de voir la forme des données, de chercher ce qu'elles contiennent, de vérifier ce qui est pertinent à garder, de voir comment les nettoyer et de transformer en un schéma SQL.

## Connexion à l'API Current Weather
Je teste la connexion à l'API qui renvoie les informations météo d'une ville. Et, aussi une API d'OpenWeather qui renvoie les coordonnées géographiques d'une ville. La clé est hardcodée uniquement pour exploration, jamais en production

In [128]:
#Importation des librairies nécessaires
import requests
import pandas as pd
import json
import os
from dotenv import load_dotenv
from sqlalchemy import select, create_engine, text, URL, Table, Column, Sequence, Integer, TIMESTAMP, Float, String, MetaData, ForeignKey

In [129]:
# Charger les variables du fichier .env
load_dotenv(dotenv_path="../.env")

True

In [3]:
cle_api = os.getenv("API_KEY_OPENWEATHER")

In [3]:
# Appel API pour les coordonnées des villes utilisées en exemple
# Libreville
params_lib = {
    'q': 'Libreville,GA',
    'appid': cle_api
}
url = "http://api.openweathermap.org/geo/1.0/direct"

r_lib = requests.get(url, params=params_lib)

geo_lib = [r_lib.json()[0]['lat'], r_lib.json()[0]['lon']]

# Paris
params_pa = {
    'q': 'Paris,FR',
    'appid': cle_api
}
url = "http://api.openweathermap.org/geo/1.0/direct"

r_pa = requests.get(url, params=params_pa)

geo_pa = [r_pa.json()[0]['lat'], r_pa.json()[0]['lon']]

# Tokyo
params_to = {
    'q': 'Tokyo,JP',
    'appid': cle_api
}
url = "http://api.openweathermap.org/geo/1.0/direct"

r_to = requests.get(url, params=params_to)

geo_to = [r_to.json()[0]['lat'], r_to.json()[0]['lon']]

# Reykjavík
params_rey = {
    'q': 'Reykjavík',
    'appid': cle_api
}
url = "http://api.openweathermap.org/geo/1.0/direct"

r_rey = requests.get(url, params=params_rey)

geo_rey = [r_rey.json()[0]['lat'], r_rey.json()[0]['lon']]

In [4]:
# Appel de l'API pour les informations météo d'une ville donnée
url = "https://api.openweathermap.org/data/2.5/weather"

# Libreville
p_weather_lib = {
    'lat': geo_lib[0],
    'lon': geo_lib[1],
    'appid': cle_api
}

r_lib = requests.get(url, params=p_weather_lib)

# Paris
p_weather_pa = {
    'lat': geo_pa[0],
    'lon': geo_pa[1],
    'appid': cle_api
}

r_pa = requests.get(url, params=p_weather_pa)

# Tokyo
p_weather_to = {
    'lat': geo_to[0],
    'lon': geo_to[1],
    'appid': cle_api
}

r_to = requests.get(url, params=p_weather_to)

# Reykjavík
p_weather_rey = {
    'lat': geo_rey[0],
    'lon': geo_rey[1],
    'appid': cle_api
}

r_rey = requests.get(url, params=p_weather_rey)

In [5]:
# Libreville
d_lib = r_lib.json()

In [6]:
# Paris
d_pa = r_pa.json()

In [7]:
# Tokyo
d_to = r_to.json()

In [8]:
# Reykjavík
d_rey = r_rey.json()

## Analyse des réponses API
Ici, on va récupérer les clés et vérifier si toutes sont présentes dans chaque réponse.
Déjà, on peut déjà juger que les données sont présentées sous le format clé-valeur. Les valeurs sont soit imbriqué, soit des listes, soit juste une valeur.

In [9]:
d_lib.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

In [10]:
d_pa.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'rain', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

In [11]:
d_to.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

In [12]:
d_rey.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'snow', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

On remarque que les clés sont les mêmes pour les quatre villes. On peut en déduire que ce sont des informations qui sont obligatoirement transmises. Analysons les clés ayant des valeurs imbriquées. On va analyser : weather, main, wind, clouds et sys.

In [13]:
print("La clé 'weather' :\n ", d_lib['weather'])
print("La clé 'main' :\n ", d_lib['main'])
print("La clé 'wind' :\n ", d_lib['wind'])
print("La clé 'clouds' :\n ", d_lib['clouds'])
print("La clé 'sys' :\n ", d_lib['sys'])

La clé 'weather' :
  [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}]
La clé 'main' :
  {'temp': 302.16, 'feels_like': 306.67, 'temp_min': 302.16, 'temp_max': 302.16, 'pressure': 1007, 'humidity': 74, 'sea_level': 1007, 'grnd_level': 1006}
La clé 'wind' :
  {'speed': 2.06, 'deg': 230}
La clé 'clouds' :
  {'all': 40}
La clé 'sys' :
  {'type': 1, 'id': 2190, 'country': 'GA', 'sunrise': 1772170319, 'sunset': 1772213895}

Ainsi, d'après nos observations, on en conclut que :
- "weather" contient une liste de clé-valeur dont les clés sont id, main, description, et icon;
- "main" contient un dictionnaire avec les clés étant temp, feels_like, temp_min, temp_max, pressure, humidity, sea_level et grnd_level;
- "wind" a pour valeur un dictionnaire avec speed et deg comme clés;
- "clouds", sa valeur est aussi un dictionnaire, mais ici, elle a seulement la clé all;
- "sys" contient un dictionnaire avec les clés type, id, country, sunrise, et sunset.

Les champs cités sont toujours présents pour les villes utilisées.

Maintenant, quelles informations seront utiles pour une office de tourisme ? 

Voici les clés qui seront gardées : coord (lat, lon), weather (main, description), main (temp, feels_like, temp_min, temp_max, pressure, humidity), visibility, wind (speed), clouds, dt, sys (country, sunrise, sunset), timezone, name (à ne pas utiliser tel quel selon les villes).
Voici les clés qui seront jetées : weather (id, icon), base, main (sea_level, grnd_level), wind (deg), sys (type, id), id, cod (on vérifiera le code renvoyé, mais on ne garde pas en mémoire).

En conclusion, le schema SQL sera le suivant :

Meteo
- main,
- description,
- temp,
- feels_like
- temp_min,
- temp_max,
- pressure,
- humidity,
- visibility
- wind_speed,
- clouds
- date
- sunrise
- sunset

Localisation
- country_name
- country_code
- city
- timezone
- lat
- lon


Les deux tables seront reliées via une relation Meteo N-1 Localisation.

## Création de la fonction de collecte
Ici, on explore la création de la fonction de collecte.

In [33]:
def init_nb_json_file() :
    conf = {
            'nb_json_file' : 0
        }
        
    with open("conf.json", "x") as json_file:
        json.dump(conf, json_file, indent=4)

In [ ]:
def collecte(cle_api, url_geo, url_meteo, city, country_code):
    # Appel API pour les coordonnées de la ville
    params_city = {
        'q': city+','+country_code,
        'appid': cle_api
    }

    r_city = requests.get(url_geo, params=params_city)

    geo_city = [r_city.json()[0]['lat'], r_city.json()[0]['lon']]

    # Appel de l'API pour les informations météo d'une ville 
    p_weather_city = {
        'lat': geo_city[0],
        'lon': geo_city[1],
        'appid': cle_api
    }
    
    r_meteo_city = requests.get(url_meteo, params=p_weather_city)

    d_city = r_meteo_city.json()

    with open("conf.json", "r") as json_file :
        conf = json.load(json_file)

    filename = "api_data"
    if conf['nb_json_file'] == 0:
        filename = "api_data.json"
    else:
        filename = filename + str(conf['nb_json_file']) +".json"
        
    cpt = conf['nb_json_file'] + 1
    conf = {
            'nb_json_file' : cpt
        }
        
    with open("conf.json", "w") as json_file:
        json.dump(conf, json_file, indent=4)

    print(f"Le fichier {filename} va être créer")
    
    with open(filename, "x") as json_file:
        json.dump(d_city, json_file, indent=4)
        
    print(f"Le fichier {filename} a été créé")
    return d_city

In [32]:
init_nb_json_file()

In [37]:
city = 'Libreville'
country = 'Gabon'

In [47]:
d_collected = collecte(cle_api, "http://api.openweathermap.org/geo/1.0/direct", "https://api.openweathermap.org/data/2.5/weather", city, 'GA')
d_collected

Le fichier api_data3.json va être créer
Le fichier api_data3.json a été créé

{'coord': {'lon': 9.454, 'lat': 0.39},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'base': 'stations',
 'main': {'temp': 302.16,
  'feels_like': 306.67,
  'temp_min': 302.16,
  'temp_max': 302.16,
  'pressure': 1007,
  'humidity': 74,
  'sea_level': 1007,
  'grnd_level': 1006},
 'visibility': 10000,
 'wind': {'speed': 2.06, 'deg': 220},
 'clouds': {'all': 20},
 'dt': 1772209197,
 'sys': {'type': 1,
  'id': 2190,
  'country': 'GA',
  'sunrise': 1772170319,
  'sunset': 1772213895},
 'timezone': 3600,
 'id': 2399697,
 'name': 'Libreville',
 'cod': 200}

## Création de la fonction de transformation des fichiers JSON
Ici, nous allons explorer l'utilisation de la fonction read_json de la bibliothèque pandas, pour pouvoir récupéré les fichiers JSON créé et les transformer en DataFrame.

In [ ]:
help(pd.read_json)

In [213]:
df_weather = pd.read_json("api_data.json", orient="columns", typ="series")

In [206]:
df_weather1 = pd.read_json("api_data1.json", orient="columns", typ="series")

En utilisant pandas, on doit ouvrir le fichier JSON en tant quue Series. Ensuite il suffit de récupérer les données dans un ou plusieurs dataFrame qui seront créés.

In [68]:
df_weather

coord                               {'lon': 9.454, 'lat': 0.39}
weather       [{'id': 803, 'main': 'Clouds', 'description': ...
base                                                   stations
main          {'temp': 301.02, 'feels_like': 304.09, 'temp_m...
visibility                                                10000
wind                  {'speed': 4.18, 'deg': 247, 'gust': 3.77}
clouds                                              {'all': 78}
dt                                                   1772208547
sys           {'country': 'GA', 'sunrise': 1772170319, 'suns...
timezone                                                   3600
id                                                      2399697
name                                                 Libreville
cod                                                         200
dtype: object

In [207]:
df_weather1

coord                               {'lon': 9.454, 'lat': 0.39}
weather       [{'id': 801, 'main': 'Clouds', 'description': ...
base                                                   stations
main          {'temp': 302.16, 'feels_like': 306.67, 'temp_m...
visibility                                                10000
wind                                {'speed': 2.06, 'deg': 220}
clouds                                              {'all': 20}
dt                                                   1772209197
sys           {'type': 1, 'id': 2190, 'country': 'GA', 'sunr...
timezone                                                   3600
id                                                      2399697
name                                                 Libreville
cod                                                         200
dtype: object

In [69]:
coord = df_weather["coord"]
weather = df_weather["weather"]
nb_weather = len(weather)
base = df_weather["base"]
main = df_weather["main"]
visibility = df_weather["visibility"]
wind = df_weather["wind"]
clouds = df_weather["clouds"]
dt = df_weather["dt"]
sys = df_weather["sys"]
timezone = df_weather["timezone"]
id_weather = df_weather["id"]
name = df_weather["name"]
cod = df_weather["cod"]

Voici les clés qui seront gardées : coord (lat, lon), weather (main, description), main (temp, temp_min, temp_max, pressure, humidity), visibility, wind (speed), clouds, dt, sys (country, sunrise, sunset), timezone, name (à ne pas utiliser tel quel selon les villes). Voici les clés qui seront jetées : weather (id, icon), base, main (sea_level, grnd_level), wind (deg), sys (type, id), id, cod (on vérifiera le code renvoyé, mais on ne garde pas en mémoire).

In [72]:
dc_meteo = {
    "main" : weather[0]['main'],
    "description" : weather[0]['description'],
    "temp" : main['temp'],
    "feels_like" : main['feels_like'],
    "temp_min" : main['temp_min'],
    "temp_max" : main['temp_max'],
    "pressure" : main['pressure'],
    "humidity" : main['humidity'],
    "visibility" : visibility,
    "wind_speed" : wind['speed'],
    "clouds" : clouds,
    "date" : dt,
    "sunrise" : sys['sunrise'],
    "sunset" : sys['sunrise']
}
dc_meteo

{'main': 'Clouds',
 'description': 'broken clouds',
 'temp': 301.02,
 'feels_like': 304.09,
 'temp_min': 301.02,
 'temp_max': 301.02,
 'pressure': 1007,
 'humidity': 74,
 'visibility': 10000,
 'wind_speed': 4.18,
 'clouds': {'all': 78},
 'date': 1772208547,
 'sunrise': 1772170319,
 'sunset': 1772170319}

In [73]:
dc_localisation = {
    "country_name" : country,
    "country_code" : sys['country'],
    "city" : city,
    "timezone" : timezone,
    "lat" : coord['lat'],
    "lon" : coord['lon']
}
dc_localisation

{'country_name': 'Gabon',
 'country_code': 'GA',
 'city': 'Libreville',
 'timezone': 3600,
 'lat': 0.39,
 'lon': 9.454}

La fonction suivante permet pour l'instant de créer un dataframe à partir du fichier JSON. Il prend en paramètre le fichier JSON ainsi que la ville et le pays, avant de le transformer en DataFrames distinct, celui contenant les données météo ainsi celui contenant les données géographique. Cela permettra de directement les utiliser telquels pour insérer dans les tables.

In [216]:
def transformer(f_json, city, country, df_updated : pd.DataFrame | None = None) :
    df_weather = pd.read_json(f_json, orient="columns", typ="series")
    rain = None
    snow = None
    
    if "rain" in df_weather.index:
        rain = df_weather["rain"]

    if "snow" in df_weather.index:
        snow = df_weather["snow"]
    
    dc_weather = {
        "main" : df_weather["weather"][0]['main'],
        "description" : df_weather["weather"][0]['description'],
        "temp" : df_weather["main"]['temp'],
        "feels_like" : df_weather["main"]['feels_like'],
        "temp_min" : df_weather["main"]['temp_min'],
        "temp_max" : df_weather["main"]['temp_max'],
        "pressure" : df_weather["main"]['pressure'],
        "humidity" : df_weather["main"]['humidity'],
        "visibility" : df_weather["visibility"],
        "wind_speed" : df_weather["wind"]['speed'],
        "clouds" : df_weather["clouds"]['all'],
        "rain" : rain,
        "snow" : snow,
        "date" : df_weather["dt"],
        "sunrise" : df_weather["sys"]['sunrise'],
        "sunset" : df_weather["sys"]['sunset'],
        "country_name" : country,
        "country_code" : df_weather["sys"]['country'],
        "city" : city,
        "timezone" : df_weather["timezone"],
        "lat" : df_weather["coord"]['lat'],
        "lon" : df_weather["coord"]['lon']
    }

    df = pd.DataFrame(dc_weather, index=[0])
    
    # Conversion des dates en format lisible
    df['date'] = pd.to_datetime(df['date'], unit='s')
    df['sunrise'] = pd.to_datetime(df['sunrise'], unit='s')
    df['sunset'] = pd.to_datetime(df['sunset'], unit='s')
    
    if df_updated is not None :
        df = pd.concat([df_updated, df], ignore_index=True)
    
    return df

In [217]:
df_weathers = transformer("api_data.json", city, country)
df_weathers

,main,description,temp,feels_like,temp_min,temp_max,pressure,humidity,visibility,wind_speed,...,snow,date,sunrise,sunset,country_name,country_code,city,timezone,lat,lon
0,Clouds,broken clouds,301.02,304.09,301.02,301.02,1007,74,10000,4.18,...,None,2026-02-27 16:09:07,2026-02-27 05:31:59,2026-02-27 17:38:15,Gabon,GA,Libreville,3600,0.39,9.454

In [212]:
if "rain" in df_weathers.columns:
    print(True)
else:
    print(False)

True

In [218]:
df_weathers = transformer("api_data1.json", city, country, df_updated = df_weathers)
df_weathers

,main,description,temp,feels_like,temp_min,temp_max,pressure,humidity,visibility,wind_speed,...,snow,date,sunrise,sunset,country_name,country_code,city,timezone,lat,lon
0,Clouds,broken clouds,301.02,304.09,301.02,301.02,1007,74,10000,4.18,...,None,2026-02-27 16:09:07,2026-02-27 05:31:59,2026-02-27 17:38:15,Gabon,GA,Libreville,3600,0.39,9.454
1,Clouds,few clouds,302.16,306.67,302.16,302.16,1007,74,10000,2.06,...,None,2026-02-27 16:19:57,2026-02-27 05:31:59,2026-02-27 17:38:15,Gabon,GA,Libreville,3600,0.39,9.454

In [229]:
df_weathers["pressure"] = df_weathers["pressure"].astype(float)
df_weathers.loc[0, "pressure"]

np.float64(1007.0)

## Accéder à la base de données

In [21]:
%pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\lenovo\appdata\roaming\python\python313\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

In [29]:
# Récupérer les variables d'environnement
host = os.getenv("DB_HOST")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
port = os.getenv("DB_PORT")
base = os.getenv("DB_NAME")

In [30]:
# Format de URL : dialecte+pilote://user:password@host:port/name_base
url_BDD = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{base}"

In [142]:
# Autre moyen de créer l'URL
url_BDDv2 = URL.create(
    "postgresql+psycopg2",
    username=user,
    password=password,
    host=host,
    database=base,
)

In [145]:
engine = create_engine(url_BDD)

In [146]:
try:
    with engine.connect() as connection:
        connection.execute(text("SELECT 1"))
    print(f"Connexion établie sur {host} avec l'utilisateur {user}.")
except Exception as e:
    print(f"Échec de la connexion à la base de données : {e}")

Connexion établie sur localhost avec l'utilisateur postgres.

In [188]:
# Création de la base de données
metadata_obj = MetaData()
tb_loc = "locations"
tb_weath = "weathers"

locations = Table(
    tb_loc,
    metadata_obj,
    Column("location_id", Integer, Sequence("location_id_seq"), primary_key=True),
    Column("country_name", String(100), nullable=False),
    Column("city", String(100), nullable=False),
    Column("country_code", String(2), nullable=False),
    Column("timezone", Integer, nullable=False),
    Column("lat", Float, nullable=False),
    Column("lon", Float, nullable=False)
)

weathers = Table(
    tb_weath,
    metadata_obj,
    Column("weather_id", Integer, Sequence("weather_id_seq"), primary_key=True),
    Column("main", String(20), nullable=False),
    Column("description", String, nullable=False),
    Column("temp", Float, nullable=False),
    Column("feels_like", Float, nullable=False),
    Column("temp_min", Float, nullable=False),
    Column("temp_max", Float, nullable=False),
    Column("pressure", Float, nullable=False),
    Column("humidity", Float, nullable=False),
    Column("visibility", Float, nullable=False),
    Column("wind_speed", Float, nullable=False),
    Column("clouds", Float, nullable=False),
    Column("rain", Float),
    Column("snow", Float),
    Column("observation_time", TIMESTAMP, nullable=False),
    Column("sunrise", TIMESTAMP, nullable=False),
    Column("sunset", TIMESTAMP, nullable=False),
    Column("location_id", None, ForeignKey("locations.location_id"), nullable=False)
)

In [236]:
try :
    metadata_obj.create_all(engine)
    print(f"Les tables {tb_loc} et {tb_weath} ont été créé dans la base de donnée {base}.")
except Exception as e:
    print(f"Échec de la création des tables : {e}")

Les tables locations et weathers ont été créé dans la base de donnée stations.

In [79]:
dc_localisation["country_name"]

'Gabon'

In [102]:
try :
    ins = locations.insert().values(
        country_name = dc_localisation["country_name"],
        country_code = dc_localisation["country_code"],
        city = dc_localisation["city"],
        timezone = dc_localisation["timezone"],
        lat = dc_localisation["lat"],
        lon = dc_localisation["lon"])
    print(f"Insertion dans la base de donnée {base}...\n") 
    print(ins.compile().params,"\n")
    with engine.begin() as connection:
        print("...Insertion en cours...")
        print(str(ins),"\n")
        resultat = connection.execute(ins)
    print(f"... Les données ont été inséré dans la table 'locations' de la base de donnée {base}")
except Exception as e :
    print(f"Échec de l'insertion : {e}")

Insertion dans la base de donnée stations...

{'location_id': None, 'country_name': 'Gabon', 'city': 'Libreville', 'country_code': 'GA', 'timezone': 3600, 'lat': 0.39, 'lon': 9.454}

...Insertion en cours...
INSERT INTO locations (location_id, country_name, city, country_code, timezone, lat, lon) VALUES (:location_id, :country_name, :city, :country_code, :timezone, :lat, :lon)

... Les données ont été inséré dans la table 'locations' de la base de donnée stations

In [177]:
try :
    with engine.connect() as connection:
        s = select(locations)
        result = connection.execute(s)
    print(result.fetchall())
except Exception as e :
        print(f"Échec de la sélection : {e}")

[(18, 'Gabon', 'Libreville', 'GA', 3600, 0.39, 9.454)]

In [172]:
def villePresente(city, engine):
    try :
        with engine.connect() as connection:
            s = select(locations)
            result = connection.execute(s)
        for line in result.fetchall() :
            if city == line[2] :
                return True
            else:
                return False
    except Exception as e :
            print(f"Échec de la sélection : {e}")

In [173]:
villePresente("Libreville", engine)

True

In [174]:
villePresente("Koulamoutou", engine)

False

In [163]:
def villeId(city, engine):
    try :
        with engine.connect() as connection:
            s = select(locations)
            result = connection.execute(s)
        for line in result.fetchall() :
            if city == line[2] :
                return line[0]
            else:
                print(f"La ville de '{city}' n'est pas présente dans la base")
    except Exception as e :
            print(f"Échec de la sélection : {e}")

In [164]:
villeId("Libreville", engine)

18

Ci-dessous nous créons la fonction qui va insérer les données du dataFrame dans la base. 
Bien sûr toute optimisation se fera lors de la création des classes. A ce moment, les fonctions devriendront des méthodes, et certaines optimisations pourront être fait.

In [234]:
def depot_sql(df):
                         
    # Récupérer les variables d'environnement
    host = os.getenv("DB_HOST")
    user = os.getenv("DB_USER")
    password = os.getenv("DB_PASSWORD")
    port = os.getenv("DB_PORT")
    base = os.getenv("DB_NAME")

    # Format de URL : dialecte+pilote://user:password@host:port/name_base
    url_BDD = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{base}"

    engine = create_engine(url_BDD)

    try:
        with engine.connect() as connection:
            connection.execute(text("SELECT 1"))
        print(f"Connexion établie sur {host} avec l'utilisateur {user}.")
    except Exception as e:
        print(f"Échec de la connexion à la base de données : {e}")

    # Insertion dans la table locations
    for i in range(len(df)):
        city = df.loc[i]['city']
        
        if not villePresente(city, engine):
            try :
                ins = locations.insert().values(
                    country_name = df.loc[i]["country_name"],
                    country_code = df.loc[i]["country_code"],
                    city = df.loc[i]["city"],
                    timezone = df.loc[i]["timezone"],
                    lat = df.loc[i]["lat"],
                    lon = df.loc[i]["lon"])
                
                print(f"Insertion dans la base de donnée {base}...\n......\n") 
                print(ins.compile().params,"\n")
                
                with engine.begin() as connection:
                    print("...Insertion en cours...")
                    print(str(ins),"\n")
                    resultat = connection.execute(ins)
                print(f"... Les données ont été inséré dans la table 'locations' de la base de donnée {base}")
            except Exception as e :
                print(f"Échec de l'insertion : {e}")

        loc_id = villeId(city, engine)

        # Insertion dans la table weathers  
        try:
            rain = df.loc[i]["rain"]
            snow = df.loc[i]["snow"]
            if rain != None:
                rain = float(rain)

            if snow != None:
                snow = float(snow)
            
            ins = weathers.insert().values(
                main = df.loc[i]["main"],
                description = df.loc[i]["description"],
                temp = float(df.loc[i]["temp"]),
                feels_like = float(df.loc[i]["feels_like"]),
                temp_min = float(df.loc[i]["temp_min"]),
                temp_max = float(df.loc[i]["temp_max"]),
                pressure = float(df.loc[i]["pressure"]),
                humidity = float(df.loc[i]["humidity"]),
                visibility = float(df.loc[i]["visibility"]),
                wind_speed = float(df.loc[i]["wind_speed"]),
                clouds = float(df.loc[i]["clouds"]),
                rain = rain,
                snow = snow,
                observation_time = df.loc[i]["date"],
                sunrise = df.loc[i]["sunrise"],
                sunset = df.loc[i]["sunset"],
                location_id = loc_id)
            
            print(f"Insertion dans la base de donnée {base}...\n......\n") 
            print(ins.compile().params,"\n")
            
            with engine.begin() as connection:
                print("...Insertion en cours...")
                print("\n",str(ins),"\n")
                resultat = connection.execute(ins)
                
            print(f"... Les données ont été inséré dans la table 'weathers' de la base de donnée {base}")
        except Exception as e :
            print(f"Échec de l'insertion : {e}")

In [180]:
len(df_weathers)

2

In [235]:
depot_sql(df_weathers)

Connexion établie sur localhost avec l'utilisateur postgres.
Insertion dans la base de donnée mt_tourisme...
......

{'weather_id': None, 'main': 'Clouds', 'description': 'broken clouds', 'temp': 301.02, 'feels_like': 304.09, 'temp_min': 301.02, 'temp_max': 301.02, 'pressure': 1007.0, 'humidity': 74.0, 'visibility': 10000.0, 'wind_speed': 4.18, 'clouds': 78.0, 'rain': None, 'snow': None, 'observation_time': Timestamp('2026-02-27 16:09:07'), 'sunrise': Timestamp('2026-02-27 05:31:59'), 'sunset': Timestamp('2026-02-27 17:38:15'), 'location_id': 18}

...Insertion en cours...

 INSERT INTO weathers (weather_id, main, description, temp, feels_like, temp_min, temp_max, pressure, humidity, visibility, wind_speed, clouds, rain, snow, observation_time, sunrise, sunset, location_id) VALUES (:weather_id, :main, :description, :temp, :feels_like, :temp_min, :temp_max, :pressure, :humidity, :visibility, :wind_speed, :clouds, :rain, :snow, :observation_time, :sunrise, :sunset, :location_id)

... Les données ont été inséré dans la table 'weathers' de la base de donnée mt_tourisme
Insertion dans la base de donnée mt_tourisme...
......

{'weather_id': None, 'main': 'Clouds', 'description': 'few clouds', 'temp': 302.16, 'feels_like': 306.67, 'temp_min': 302.16, 'temp_max': 302.16, 'pressure': 1007.0, 'humidity': 74.0, 'visibility': 10000.0, 'wind_speed': 2.06, 'clouds': 20.0, 'rain': None, 'snow': None, 'observation_time': Timestamp('2026-02-27 16:19:57'), 'sunrise': Timestamp('2026-02-27 05:31:59'), 'sunset': Timestamp('2026-02-27 17:38:15'), 'location_id': 18}

...Insertion en cours...

 INSERT INTO weathers (weather_id, main, description, temp, feels_like, temp_min, temp_max, pressure, humidity, visibility, wind_speed, clouds, rain, snow, observation_time, sunrise, sunset, location_id) VALUES (:weather_id, :main, :description, :temp, :feels_like, :temp_min, :temp_max, :pressure, :humidity, :visibility, :wind_speed, :clouds, :rain, :snow, :observation_time, :sunrise, :sunset, :location_id)

... Les données ont été inséré dans la table 'weathers' de la base de donnée mt_tourisme